# Generated by Django 3.2.4 on 2021-07-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20210712_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='role',
        ),
    ]
