# Generated by Django 3.2.4 on 2021-07-12 08:04

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('state_of_origin', models.CharField(choices=[('oyo', 'Oyo'), ('ogun', 'Ogun'), ('osun', 'Osun'), ('lagos', 'Lagos'), ('ondo', 'Ondo'), ('kwara', 'Kwara'), ('kogi', 'Kogi'), ('ekiti', 'ekiti'), ('delta', 'Delta')], max_length=12)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=8)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
                ('date_of_birth', models.DateField()),
                ('employment_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='default.png', upload_to='staff/images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Staff Document', max_length=30)),
                ('file', models.FileField(upload_to='files/None')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='employees.employee')),
            ],
        ),
    ]
