# Generated by Django 3.2.4 on 2021-07-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('security officer', 'Security Officer'), ('senior security officer', 'Senior Security Officer'), ('driver', 'Driver'), ('senior driver', 'Senior Driver'), ('cleaner', 'Cleaner'), ('senior cleaner', 'Senior Cleaner'), ('it officer', 'IT Officer'), ('it Consultant', 'IT Consultant'), ('communications officer', 'Communications Officer'), ('accounts assistant', 'Accounts Assistant'), ('accountant', 'Accountant'), ('senior accountant', 'Senior Accountant'), ('finance manager', 'Finance Manager'), ('research assistant', 'Research Assistant'), ('data manager', 'Data Manager'), ('m&e officer', 'M&E Officer'), ('medical advisor', 'Medical Advisor'), ('senior medical advisor', 'Senior Medical Advisor'), ('medical coordinator', 'Medical Coordinator'), ('admin assistant', 'Admin Assistant'), ('admin officer', 'Admin Officer'), ('office manager', 'Office Manager'), ('operations & hr', 'Operations & HR'), ('deputy country rep', 'Deputy Country Rep'), ('country rep', 'Country Rep')], max_length=50, null=True),
        ),
    ]
