# Generated by Django 3.2.4 on 2021-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_remove_donor_staff'),
        ('employees', '0003_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='donors',
            field=models.ManyToManyField(to='donors.Donor', verbose_name='Donors'),
        ),
    ]
