# Generated by Django 3.2.4 on 2021-10-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_staffdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
