# Generated by Django 3.2.4 on 2021-10-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdocument',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
